// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgSt7TJSVVyDOnllVqyfCpwpjY-tYXemY',
    appId: '1:254546507951:web:8a163707d2dc31156b3c5a',
    messagingSenderId: '254546507951',
    projectId: 'getcontact-b7674',
    authDomain: 'getcontact-b7674.firebaseapp.com',
    databaseURL: 'https://getcontact-b7674.firebaseio.com',
    storageBucket: 'getcontact-b7674.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPyrK2K2uSVCODWP7rP7V__7eRoQqsmRE',
    appId: '1:254546507951:android:9dc2eb234de86da26b3c5a',
    messagingSenderId: '254546507951',
    projectId: 'getcontact-b7674',
    databaseURL: 'https://getcontact-b7674.firebaseio.com',
    storageBucket: 'getcontact-b7674.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdDu2_-qXm7cFXLGNC_RLHp1P8tx3Wytc',
    appId: '1:254546507951:ios:bc8c4f3277d1a7246b3c5a',
    messagingSenderId: '254546507951',
    projectId: 'getcontact-b7674',
    databaseURL: 'https://getcontact-b7674.firebaseio.com',
    storageBucket: 'getcontact-b7674.appspot.com',
    iosClientId: '254546507951-o6sscgkp4k0jedi5uknc9rebe53fk5j2.apps.googleusercontent.com',
    iosBundleId: 'com.example.xAppa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdDu2_-qXm7cFXLGNC_RLHp1P8tx3Wytc',
    appId: '1:254546507951:ios:bc8c4f3277d1a7246b3c5a',
    messagingSenderId: '254546507951',
    projectId: 'getcontact-b7674',
    databaseURL: 'https://getcontact-b7674.firebaseio.com',
    storageBucket: 'getcontact-b7674.appspot.com',
    iosClientId: '254546507951-o6sscgkp4k0jedi5uknc9rebe53fk5j2.apps.googleusercontent.com',
    iosBundleId: 'com.example.xAppa',
  );
}
